# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20171205_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_confirm',
            new_name='has_confirmed',
        ),
    ]
